### ISSUE TITLE
Unable to run sample on Windows

### ISSUE THREAD

**Issue by rince1013** [findify/s3mock#9] opened 2016-10-24 19:42 UTC
Running the sample code on Windows fails with an error

> [ERROR] [10/24/2016 19:38:55.332] [sqsmock-akka.actor.default-dispatcher-7] [akka.actor.ActorSystemImpl(sqsmock)] Error during processing of request HttpRequest(HttpMethod(PUT),http://127.0.0.1:8001/testbucket/file/name,List(Host: 127.0.0.1:8001, user-agent: aws-sdk-java/1.11.41 Windows_7/6.1 Java_HotSpot(TM)_64-Bit_Server_VM/25.74-b02/1.8.0_74, amz-sdk-invocation-id: 4d329e5c-1ebc-f226-f93a-5182d9d93f9d, amz-sdk-retry: 0/0/500, Connection: Keep-Alive, Expect: 100-continue, Timeout-Access: <function1>),HttpEntity.Default(text/plain; charset=UTF-8,8 bytes total),HttpProtocol(HTTP/1.1))
> java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:\tmp\s3
>   at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
>   at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
>   at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
>   at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
>   at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
>   at java.nio.file.Paths.get(Paths.java:84)
>   at better.files.File$.apply(File.scala:801)
>   at io.findify.s3mock.provider.FileProvider.create$1(FileProvider.scala:108)
>   at io.findify.s3mock.provider.FileProvider.createDir(FileProvider.scala:112)
>   at io.findify.s3mock.provider.FileProvider.putObject(FileProvider.scala:54)
>   at io.findify.s3mock.route.PutObject$$anonfun$completePlain$1$$anonfun$apply$4$$anonfun$4.apply(PutObject.scala:49)
>   at io.findify.s3mock.route.PutObject$$anonfun$completePlain$1$$anonfun$apply$4$$anonfun$4.apply(PutObject.scala:48)
>   at akka.stream.impl.fusing.Map$$anon$5.onPush(Ops.scala:42)
>   at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:755)
>   at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:744)
>   at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:624)
>   at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:470)
>   at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:422)
>   at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:602)
>   at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:617)
>   at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
>   at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:528)
>   at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
>   at akka.actor.ActorCell.invoke(ActorCell.scala:495)
>   at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
>   at akka.dispatch.Mailbox.run(Mailbox.scala:224)
>   at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
>   at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
>   at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
>   at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
>   at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Test Class

```
import com.amazonaws.auth.AnonymousAWSCredentials;
import com.amazonaws.services.s3.AmazonS3Client;
import io.findify.s3mock.S3Mock;
import org.junit.Test;

public class FakeS3 {

    @Test
    public void testFakeS3(){
        S3Mock api = S3Mock.create(8001, "C:\\tmp\\s3");
        api.start();

        AmazonS3Client client = new AmazonS3Client(new AnonymousAWSCredentials());
        // use IP endpoint to override DNS-based bucket addressing
        client.setEndpoint("http://127.0.0.1:8001");
        client.createBucket("testbucket");
        client.putObject("testbucket", "file/name", "contents");
    }
}
```

**Comment by mpaluchowski** [comment] 2016-11-23 13:32
Same issue here. The problem is shown in the log line:

```
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:\tmp\s3
```

s3mock's code prefixes the path you provided `C:\tmp\s3` with a slash `/`, which then causes the exception. Overall, looking at `io/findify/s3mock/provider/FileProvider.scala` the code there assumes running on a *nix machine and uses hard-coded slashes extensively, instead of some equivalent of Java's `System.getProperty("file.separator")`.

**Comment by shuttie** [comment] 2016-12-03 10:28
fixed in https://github.com/findify/s3mock/pull/13

**Closed by shuttie** 2016-12-03 10:28 UTC
